Load device after trace logger as been configured
as device.py loads and uses the logger with the trace method, which does not exist until configure_trace_logging() has been called, hence produces:
```
AttributeError: 'Logger' object has no attribute 'trace'
```

Regression introduced with: https://github.com/truenas/py-SMART/commit/5c43f7ad3316651fe9336ff87af3f8239290b306

Signed-off-by: MichaIng <micha@dietpi.com>